### PR TITLE
Nausheen_S-tunr_app

### PR DESCRIPTION
**Pull request by ghost**
**Deliverable Submission**

Please describe your comfort and completeness levels before submitting. Comfort Level (1-5):3

Completeness Level (1-5):
3
How many hours did you spend on this assignment?2

What part did you spend the most time on?rendering using form

Does the assignment run without errors? yes
If the assignment has errors, what are they?

Describe one part of the code or choose one line you would improve upon. What would you improve?

What did you think of this deliverable? Any other comments?

### CODE REVIEW

**Comment by Nausheen-S** [comment]
completed part 2

**Comment by Nausheen-S** [comment]
Please describe your comfort and completeness levels before submitting. Comfort Level (1-5):3

Completeness Level (1-5):
3
How many hours did you spend on this assignment?4

What part did you spend the most time on?rendering using form

Does the assignment run without errors? yes
If the assignment has errors, what are they?

Describe one part of the code or choose one line you would improve upon. What would you improve?

What did you think of this deliverable? Any other comments?

**Comment by ghost** [comment]
Deliverable Submission

Please describe your comfort and completeness levels before submitting. Comfort Level (1-5):3

Completeness Level (1-5):
3
How many hours did you spend on this assignment?1

What part did you spend the most time on?spent same time on everything

Does the assignment run without errors? yes
If the assignment has errors, what are they?

Describe one part of the code or choose one line you would improve upon. What would you improve?

What did you think of this deliverable? Any other comments?

**Comment by ghost** [comment]
Deliverable Submission

Please describe your comfort and completeness levels before submitting. Comfort Level (1-5):3

Completeness Level (1-5):
3
How many hours did you spend on this assignment?2

What part did you spend the most time on?rendering using form

Does the assignment run without errors? yes
If the assignment has errors, what are they?

Describe one part of the code or choose one line you would improve upon. What would you improve?

What did you think of this deliverable? Any other comments?

**Pull request closed without merging**
